// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Examen_AlejandroRC;

/************************************************************/
/**
 * 
 */
public class Camareros extends Personal {
}
