// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Examen_AlejandroRC;

/************************************************************/
/**
 * 
 */
public class Clientes extends Personas {
	/**
	 * 
	 */
	public Pedidos[] pedidos;
}
