// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Examen_AlejandroRC;

/************************************************************/
/**
 * 
 */
public class Gerentes extends Personal {
	/**
	 * 
	 */
	public Personal[] personal;

	/**
	 * 
	 */
	public void dar_alta_baja() {
	}

	/**
	 * 
	 */
	public void modo_supervisor() {
	}
}
