// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Examen_AlejandroRC;

/************************************************************/
/**
 * 
 */
public class info_pedido {
	/**
	 * 
	 */
	protected String fecha;
	/**
	 * 
	 */
	protected String hora;
	/**
	 * 
	 */
	protected float precio_total;

	/**
	 * 
	 * @param fecha 
	 * @param hora 
	 * @param precio 
	 */
	public void asignar_valores(String fecha, String hora, float precio) {
	}
}
