// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Examen_AlejandroRC;

/************************************************************/
/**
 * 
 */
public class Pedidos {
	/**
	 * 
	 */
	protected String Nombre;
	/**
	 * 
	 */
	protected double Precio;

	/**
	 * 
	 * @param nom 
	 * @param precio 
	 */
	public void asignar_valores(String nom, double precio) {
	}
}
