// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Examen_AlejandroRC;

/************************************************************/
/**
 * 
 */
public class Personas {
	/**
	 * 
	 */
	protected String DNI;
	/**
	 * 
	 */
	protected String Nombre;
	/**
	 * 
	 */
	protected String Telefono;
	/**
	 * 
	 */
	protected String Usuario;
	/**
	 * 
	 */
	protected String Password;

	/**
	 * 
	 * @param dni 
	 * @param nom 
	 * @param tlf 
	 * @param usuario 
	 * @param pass 
	 */
	public void asignar_valores(String dni, String nom, String tlf, String usuario, String pass) {
	}
}
