// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Examen_AlejandroRC;

/************************************************************/
/**
 * 
 */
public class Personal extends Personas {
	/**
	 * 
	 */
	protected String Fecha_contratacion;
	/**
	 * 
	 */
	protected float salario;

	/**
	 * 
	 * @param fecha_contratacion 
	 * @param salario 
	 */
	public void asignar_valores(String fecha_contratacion, float salario) {
	}
}
